messages:
  self healed: "&a&l(!) &aYou have been healed!"
  other healed: "&a&l(!) &a&l{PLAYER_NAME} &ahas been healed!" #Valid placeholders: {PLAYER_NAME} - Player name, {PLAYER_DISPLAYNAME} - Player Displayname
  other healed by: "&a&l(!) &aYou were healed by &a&l{HEALED_BY_PLAYER_NAME}" #Valid Placeholders: {HEALED_BY_PLAYER_NAME} - Player name of player that healed them, {HEALED_BY_PLAYER_DISPLAYNAME} - Player displayname of player that healed them
  no permission: "&c&l(!) &cNo Permission"
  
settings:
  tell other player they were healed: true