on:
 push:
   tags:
   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10 
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Generate build number
      uses: einaregilsson/build-number@v1
      id: buildnumber
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run Helper
      id: helper
      run: "chmod +x ./.github/release-helper && bash ./.github/release-helper"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Discord Success Message
      if: success()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#32cd32"
        message: "**[RandomHeal - Build ${{ steps.buildnumber.outputs.build_number }}]**\n\nBuild Success!\nChanges:\n${{ steps.helper.outputs.COMMIT_MESSAGE }}"
        
    - name: Discord Failure Message
      if: failure()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#f70d1a"
        message: "**[RandomHeal - Build ${{ steps.buildnumber.outputs.build_number }}]**\n\nBuild Failed!\nChanges:\n${{ steps.helper.outputs.COMMIT_MESSAGE }}"
      
    - name: Make Artifact Directory
      run: "mkdir ./artifacts"
    
    - name: Find and Move JARS
      run: "mv `find target -name *.jar -print` ./artifacts"

    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@master
      with:
        name: Artifacts
        path: "./artifacts"
    
    - name: Create Release
      id: create_release
      if: success()
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: build-number-${{ steps.buildnumber.outputs.build_number }}
        release_name: Build ${{ steps.buildnumber.outputs.build_number }}
        draft: false
        prerelease: false

    - name: Upload asset to release
      uses: Puyodead1/upload-release-asset@feature-glob
      id: upload-release-asset 
      if: success()
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}

    - name: Discord Success Message
      if: success()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#32cd32"
        message: "**[RandomHeal - Build ${{ steps.buildnumber.outputs.build_number }}]**\nNew Release!\n\n**Download:** ${{ steps.upload-release-asset.outputs.browser_download_url }}\nChanges:\n${{ steps.helper.outputs.COMMIT_MESSAGE }}"
