name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: List
      run: "ls"
    - name: Upload artifact
      uses: actions/upload-artifact@master
      if: success()
      with:
        name: RandomHeal
        path: "./target/RandomHeal-v1.0.0.jar"

#     - name: Upload Release
#       uses: JasonEtco/upload-to-release@v0.1.1
#       if: success()
#       with:
#         args: "/home/runner/work/RandomHeal/RandomHeal/target/*.jar"
#       env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_ }}

    - name: Discord success notification
      if: success()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '[RandomHeal] Build Success!'

    - name: Discord failure notification
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '[RandomHeal] Build Failed!'
