name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Archive using zip or tar
      uses: juankaram/archive-action@v1.0.0
      with:
        args: "zip -r artifact.zip ./target/*.jar"

#     - name: Discord notification
#       env:
#         DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#       uses: Ilshidur/action-discord@master
#       with:
#         args: '[RandomHeal] Build Complete'
#     - name: Upload Release
#       uses: JasonEtco/upload-to-release@v0.1.1
#       with:
#         args: target\*.jar
#       env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
